import type { BaseCardData } from "./types";

const data: Array<BaseCardData> = [
    {
        id: 1,
        answer: 'Death Valley',
        name: 'Death Valley',
        shortDescription: "Is that snow on the hottest place on Earth? Visit Badwater Basin to find out for yourself.\nThe otherwordly landscapes you'll encounter will include desert sand dunes and painted hills.\nUnsurprisingly the lowest and driest place in the country is not very populated, making it an ideal dark sky to look for the aliens commonly thought to reside in nearby Area 51.\nLook for UFOs amongst the Ursids in tonight's meteor shower.",
        image: '/images/death-valley.jpg',
        slug: 'death-valley',
    },
    {
        id: 2,
        answer: 'fire',
        name: 'Valley of Fire',
        shortDescription: "Not feeling the slot machines? Try visiting a slot canyon instead, reminiscent of its cousins at Zion National Park.\nIf you're more in the mood for art, make sure to check out the petroglyphs made by artists 4,000 years ago!\n Finally, channel your inner safari guide and see if you can spot an elephant at the Valley of Fire!",
        image: '/images/valleyoffire.webp',
        slug: 'valley-of-fire',
    },
    {
        id: 3,
        answer: 'Magic',
        name: 'Shin Lim',
        shortDescription: "The only two time America's Got Talent winner, Shin Lim ",
        image: '/images/death-valley.jpg',
        slug: 'shin-lim',
    },
    {
        id: 4,
        answer: 'glass',
        name: 'Glass Making Class',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'glass',
    },
    {
        id: 5,
        answer: 'Ramsay',
        name: 'Gordon Ramsay Burger',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'gordon-ramsay-burger',
    },
    {
        id: 6,
        answer: 'cards',
        name: 'Casino Quest',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'casino-quest',
    },
    {
        id: 7,
        answer: '',
        name: 'China Poblano',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'china-poblano',
    },
    {
        id: 8,
        answer: 'eau',
        name: 'O Cirque du Soleil',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'o-cirque',
    },
    {
        id: 9,
        answer: 'Thomas Keller',
        name: 'Bouchon',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'bouchon-brunch',
    },
    {
        id: 10,
        answer: 'Escape',
        name: 'The Escape Game',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'the-escape-game',
    },
    {
        id: 11,
        answer: 'Sphere',
        name: 'The Sphere',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'the-sphere',
    },
    {
        id: 12,
        answer: 'XLB',
        name: 'Din Tai Fung',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'din-tai-fung',
    }
];

export default data;