import type { BaseCardData } from "./types";

const data: Array<BaseCardData> = [
    {
        id: 1,
        answer: 'Death Valley',
        name: 'Death Valley',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'death-valley',
    },
    {
        id: 2,
        answer: 'fire',
        name: 'Valley of Fire',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'valley-of-fire',
    },
    {
        id: 3,
        answer: 'Magic',
        name: 'Shin Lim',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'shin-lim',
    },
    {
        id: 4,
        answer: 'glass',
        name: 'Glass Making Class',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'glass',
    },
    {
        id: 5,
        answer: 'Ramsay',
        name: 'Gordon Ramsay Burger',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'gordon-ramsay-burger',
    },
    {
        id: 6,
        answer: 'cards',
        name: 'Casino Quest',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'casino-quest',
    },
    {
        id: 7,
        answer: '',
        name: 'China Poblano',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'china-poblano',
    },
    {
        id: 8,
        answer: 'eau',
        name: 'O Cirque du Soleil',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'o-cirque',
    },
    {
        id: 9,
        answer: 'Thomas Keller',
        name: 'Bouchon',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'bouchon-brunch',
    },
    {
        id: 10,
        answer: 'Escape',
        name: 'The Escape Game',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'the-escape-game',
    },
    {
        id: 11,
        answer: 'Sphere',
        name: 'The Sphere',
        shortDescription: 'Death Valley is a valley in the Mojave Desert of the United States. It is known for its extreme heat and dryness.',
        image: '/images/death-valley.jpg',
        slug: 'the-sphere',
    },
    {
        id: 12,
        answer: 'XLB',
        name: 'Din Tai Fung',
        shortDescription: 'Valley of Fire is a ',
        image: '/images/valley-of-fire.jpg',
        slug: 'din-tai-fung',
    }
];

export default data;